### ISSUE TITLE
Purpose of NoEncryption plugin?

### ISSUE THREAD

**Issue by nerdstein** [nerdstein/encrypt#12]
I dont understand why it's there

**Comment by mjl3475** [comment]
There was a plugin in the D7 version for no encryption. I just ported it over. Made for a good template. Maybe it should be converted to being the Base plugin?

**Comment by nerdstein** [comment]
Base plugin is not really needed with the interface.

We likely can remove it, but @rlhawk do you have an opinion?

**Comment by rlhawk** [comment]
It's useful for testing, but that's about it. I say we drop it. It's trivial to reproduce in a separate module, if anyone actually misses it.

**Comment by mjl3475** [comment]
branch/Issue-12-26-remove-basic-and-no-encryption
